"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var fs_1 = require("fs");
var path_1 = require("path");
require("amd-loader");
require("reflect-metadata");
var config_1 = require("./config");
var errors_1 = tslib_1.__importStar(require("../../errors"));
var filesystem_1 = require("../../utils/filesystem");
var styledLogger_1 = require("../../utils/styledLogger");
var packages_1 = require("../../utils/packages");
var errors_2 = tslib_1.__importDefault(require("../../../codegen/errors"));
var beagle_module_1 = require("../../../codegen/compiled/beagle.module");
function getBeagleMetadataFromExports(allExports) {
    var keys = Object.keys(allExports);
    var beagleModuleName;
    var config;
    keys.forEach(function (key) {
        config = Reflect.getMetadata('beagleConfig', allExports[key]);
        if (config)
            beagleModuleName = key;
    });
    if (!beagleModuleName) {
        throw new errors_1.default('Could not find a beagle module. Please, make sure you annotated your class with @BeagleModule');
    }
    return { beagleModuleName: beagleModuleName, config: config };
}
function getBeagleMetadata(beagleModulePath) {
    var beagleFileExports;
    try {
        beagleFileExports = require(beagleModulePath);
    }
    catch (error) {
        if (typeof error.message !== 'string')
            throw error;
        if (error.message.startsWith('Cannot find module')) {
            throw new errors_1.default("Could not find the beagle module file at \"" + beagleModulePath + "\".");
        }
        if (error.message.match('Unable to compile TypeScript')) {
            throw new errors_1.default("Unable to compile TypeScript, see the error below:\n\n" + error.message);
        }
        throw error;
    }
    return getBeagleMetadataFromExports(beagleFileExports);
}
function start() {
    var viewEngineConfig = config_1.getViewEngineConfig();
    var _a = getBeagleMetadata(viewEngineConfig.beagleModulePath), beagleModuleName = _a.beagleModuleName, config = _a.config;
    var beagleModuleCopyPath = config_1.getBeagleModuleCopyPath(viewEngineConfig.beagleModulePath);
    var fileContent;
    try {
        fileContent = beagle_module_1.generateViewEngineCode({
            config: config,
            beagleModuleName: beagleModuleName,
            beagleModuleCopyPath: filesystem_1.getImportFilePath(viewEngineConfig.outputPath, beagleModuleCopyPath),
            angularVersion: packages_1.getPackageVersion('@angular/core'),
        });
    }
    catch (error) {
        if (error.name !== errors_2.default.name)
            throw error;
        throw new errors_1.default(error.message + ". Be sure you replaced all \"todos\" in the boilerplate code generated by beagle init.");
    }
    filesystem_1.ensureDirectoryExistence(viewEngineConfig.outputPath);
    fs_1.writeFileSync(viewEngineConfig.outputPath, fileContent);
    fs_1.copyFileSync(viewEngineConfig.beagleModulePath, beagleModuleCopyPath);
    styledLogger_1.logSuccess("Beagle module files have been successfully generated at \"" + path_1.dirname(viewEngineConfig.outputPath) + "\"!");
}
exports.start = start;
try {
    start();
}
catch (error) {
    if (!errors_1.isBeagleCliError)
        throw error;
    styledLogger_1.logError(error.message);
    process.exit(error.exitCode);
}
