"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var formatting_1 = require("../../utils/formatting");
function createCommentaryString() {
    var commentary = "\n    /**\n     * BEAGLE-ANGULAR\n     *\n     * Please, do not change this file.\n     *\n     * This file has been automatically generated by the lib beagle-angular. This is necessary when\n     * the project uses ViewEngine instead of Ivy.\n     *\n     * This file should be regenerated every time a component in your beagle configuration is added,\n     * removed or its inputs are changed. To regenerate it, run:\n     * yarn beagle view-engine\n     **/\n  ";
    return formatting_1.removeExtraIndentation(commentary, 4);
}
exports.createCommentaryString = createCommentaryString;
